polar:
  greeting: Welcome to our book catalog synchronized wit Argo CD Change01!
spring:
  config:
    import: configtree:/workspace/secrets/*/

logging:
  pattern: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"