apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/corlovito/catalog_service//k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml
- patch-startprobe.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/corlovito/catalog-service/sha256
  newTag: ccafead7be7eecf755b01eeaa9894d61de2299482e1fd2e6438f96ef7e4ce852

replicas:
- count: 2
  name: catalog-service
