apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/corlovito/catalog_service//k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml
- patch-startprobe.yml
- patch-automountServiceAccount.yml
- patch-image.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

openapi:
  path: 'https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json'
