apiVersion:  argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog-service
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:

        - name: catalog-service
