apiVersion:  argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/corlovito/catalog-service:dd0689293006aa8bbec5d923294ac0bc6512b286
