apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog-service
spec:
  strategy:
    blueGreen: null
    canary:
      #canaryService: rollout-bluegreen-preview
      #stableService: catalog-service
      steps:
        - setWeight: 20
        - pause: {}
          #- pause: { duration: 40s }
        - setWeight: 50
        - pause: {}
          #- pause: { duration: 40s }
        - setWeight: 100
  analysis:
    templates:
      - templateName: canary-analysis
    args:
      - name: success-rate
        value: "90"
  revisionHistoryLimit: 2

