apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalog-service
spec:
  minReadySeconds: 30
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
