apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/corlovito/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml
- patch-probe.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
  - name: order-service
    newName: ghcr.io/corlovito/order-service
    newTag: latest

replicas:
- count: 1
  name: order-service
