# patch-resources.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  template:
    spec:
      containers:
      - name: order-service
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9002
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9002
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
