apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/corlovito/edge-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml
- patch-probe.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/corlovito/edge-service
  newTag: b5b8c4e69682b0aff11e020a68e91ae4894be541

replicas:
- count: 1
  name: edge-service
